-- MySQL Script generated by MySQL Workbench
-- Tue May 31 20:34:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_109403034
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_109403034` ;

-- -----------------------------------------------------
-- Schema db_109403034
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_109403034` DEFAULT CHARACTER SET utf8 ;
USE `db_109403034` ;

-- -----------------------------------------------------
-- Table `db_109403034`.`Member_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`Member_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`Member_table` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `salt` CHAR(64) NOT NULL,
  `gender` TINYINT NULL,
  `birth_date` VARCHAR(64) NULL,
  `address` VARCHAR(255) NULL,
  `email` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(64) NULL,
  PRIMARY KEY (`member_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`MemberCredential_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`MemberCredential_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`MemberCredential_table` (
  `member_credential_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `hashed_password` VARCHAR(200) NULL,
  INDEX `member_id_idx` (`member_id` ASC) VISIBLE,
  PRIMARY KEY (`member_credential_id`),
  CONSTRAINT `member_id_member_credential_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403034`.`Member_table` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`Category_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`Category_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`Category_table` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`Proposal_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`Proposal_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`Proposal_table` (
  `proposal_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `content` TEXT NULL,
  `goal` INT NOT NULL,
  `status` INT NOT NULL,
  `amount` INT NULL,
  `viewed_num` INT NULL,
  `create_date` DATE NOT NULL,
  `due_date` DATE NULL,
  PRIMARY KEY (`proposal_id`),
  INDEX `catogery_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `catogery`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_109403034`.`Category_table` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`ProposalOption_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`ProposalOption_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`ProposalOption_table` (
  `proposal_option_id` INT NOT NULL,
  `proposal_id` INT NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`proposal_option_id`, `proposal_id`),
  INDEX `proposal_id_idx` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `proposal_id_proposal_option_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403034`.`Proposal_table` (`proposal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`Comment_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`Comment_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`Comment_table` (
  `comment_id` INT NOT NULL,
  `proposal_id` INT NOT NULL,
  `member_id` INT NULL,
  `user_comment` TEXT NULL,
  `proposer_response` TEXT NULL,
  `status` TINYINT NULL,
  `create_at` DATE NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `proposal_id_idx` (`proposal_id` ASC) VISIBLE,
  INDEX `member_id_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `proposal_id_comment_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403034`.`Proposal_table` (`proposal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_comment_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403034`.`Member_table` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`FAQ_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`FAQ_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`FAQ_table` (
  `FAQ_id` INT NOT NULL,
  `proposal_id` INT NOT NULL,
  `member_id` INT NULL,
  `question` VARCHAR(120) NULL,
  `answer` TEXT NULL,
  PRIMARY KEY (`FAQ_id`, `proposal_id`),
  INDEX `proposal_id_idx` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `proposal_id_FAQ_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403034`.`Proposal_table` (`proposal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`ProposalMember_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`ProposalMember_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`ProposalMember_table` (
  `proposal_member_id` INT NOT NULL,
  `member_id` INT NULL,
  `proposal_id` INT NULL,
  PRIMARY KEY (`proposal_member_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`SponsorRecord_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`SponsorRecord_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`SponsorRecord_table` (
  `member_id` INT NOT NULL,
  `proposal_id` INT NOT NULL,
  `proposal_option_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `amount` INT NOT NULL,
  `create_at` DATE NULL,
  INDEX `proposal_id_idx` (`proposal_id` ASC) VISIBLE,
  PRIMARY KEY (`member_id`),
  CONSTRAINT `member_id_sponsor_record_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403034`.`Member_table` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proposal_id_sponsor_record_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403034`.`Proposal_table` (`proposal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`FollowingRecord_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`FollowingRecord_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`FollowingRecord_table` (
  `following_record_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `proposal_id` INT NULL,
  PRIMARY KEY (`following_record_id`),
  INDEX `member_id_idx` (`member_id` ASC) VISIBLE,
  INDEX `proposal_id_idx` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `member_id_following_record_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403034`.`Member_table` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proposal_id_following_record_fk`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403034`.`Proposal_table` (`proposal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`Proposal_table_has_ProposalMember_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`Proposal_table_has_ProposalMember_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`Proposal_table_has_ProposalMember_table` (
  `Proposal_table_proposal_id` INT NOT NULL,
  `ProposalMember_table_proposal_member_id` INT NOT NULL,
  INDEX `fk_Proposal_table_has_ProposalMember_table_ProposalMember_t_idx` (`ProposalMember_table_proposal_member_id` ASC) VISIBLE,
  INDEX `fk_Proposal_table_has_ProposalMember_table_Proposal_table1_idx` (`Proposal_table_proposal_id` ASC) VISIBLE,
  PRIMARY KEY (`ProposalMember_table_proposal_member_id`),
  CONSTRAINT `fk_Proposal_table_has_ProposalMember_table_Proposal_table1`
    FOREIGN KEY (`Proposal_table_proposal_id`)
    REFERENCES `db_109403034`.`Proposal_table` (`proposal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proposal_table_has_ProposalMember_table_ProposalMember_tab1`
    FOREIGN KEY (`ProposalMember_table_proposal_member_id`)
    REFERENCES `db_109403034`.`ProposalMember_table` (`proposal_member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`Member_table_has_Proposal_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`Member_table_has_Proposal_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`Member_table_has_Proposal_table` (
  `Member_table_member_id` INT NOT NULL,
  `Member_table_FollowingRecord_table_following_record_id` INT NOT NULL,
  `Proposal_table_proposal_id` INT NOT NULL,
  `Proposal_table_Category_table_category_id` INT NOT NULL,
  PRIMARY KEY (`Member_table_member_id`, `Member_table_FollowingRecord_table_following_record_id`, `Proposal_table_proposal_id`, `Proposal_table_Category_table_category_id`),
  INDEX `fk_Member_table_has_Proposal_table_Proposal_table1_idx` (`Proposal_table_proposal_id` ASC, `Proposal_table_Category_table_category_id` ASC) VISIBLE,
  INDEX `fk_Member_table_has_Proposal_table_Member_table1_idx` (`Member_table_member_id` ASC, `Member_table_FollowingRecord_table_following_record_id` ASC) VISIBLE,
  CONSTRAINT `fk_Member_table_has_Proposal_table_Member_table1`
    FOREIGN KEY (`Member_table_member_id`)
    REFERENCES `db_109403034`.`Member_table` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_table_has_Proposal_table_Proposal_table1`
    FOREIGN KEY (`Proposal_table_proposal_id`)
    REFERENCES `db_109403034`.`Proposal_table` (`proposal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403034`.`Member_table_has_ProposalMember_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403034`.`Member_table_has_ProposalMember_table` ;

CREATE TABLE IF NOT EXISTS `db_109403034`.`Member_table_has_ProposalMember_table` (
  `Member_table_member_id` INT NOT NULL,
  `ProposalMember_table_proposal_member_id` INT NOT NULL,
  PRIMARY KEY (`ProposalMember_table_proposal_member_id`),
  INDEX `fk_Member_table_has_ProposalMember_table_ProposalMember_tab_idx` (`ProposalMember_table_proposal_member_id` ASC) VISIBLE,
  INDEX `fk_Member_table_has_ProposalMember_table_Member_table1_idx` (`Member_table_member_id` ASC) VISIBLE,
  CONSTRAINT `fk_Member_table_has_ProposalMember_table_Member_table1`
    FOREIGN KEY (`Member_table_member_id`)
    REFERENCES `db_109403034`.`Member_table` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_table_has_ProposalMember_table_ProposalMember_table1`
    FOREIGN KEY (`ProposalMember_table_proposal_member_id`)
    REFERENCES `db_109403034`.`ProposalMember_table` (`proposal_member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
